# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: true

repos:
-   repo: local
    rev: v4_yarax
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: fix-byte-order-marker
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
        args: ['--maxkb=896']
    -   id: reformat-yara-x-rules
        name: Reformat Yara-X Rule Files
        language: system
        fail_fast: true
        entry: yr fmt
        types: [file]
        files: '\.yar$'
