// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: excel_unpriv_rpc.proto

package pbrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlAction int32

const (
	ControlAction_CONTROL_ACTION_UNKNOWN ControlAction = 0
	ControlAction_PING                   ControlAction = 1
	ControlAction_QUIT                   ControlAction = 2
)

// Enum value maps for ControlAction.
var (
	ControlAction_name = map[int32]string{
		0: "CONTROL_ACTION_UNKNOWN",
		1: "PING",
		2: "QUIT",
	}
	ControlAction_value = map[string]int32{
		"CONTROL_ACTION_UNKNOWN": 0,
		"PING":                   1,
		"QUIT":                   2,
	}
)

func (x ControlAction) Enum() *ControlAction {
	p := new(ControlAction)
	*p = x
	return p
}

func (x ControlAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlAction) Descriptor() protoreflect.EnumDescriptor {
	return file_excel_unpriv_rpc_proto_enumTypes[0].Descriptor()
}

func (ControlAction) Type() protoreflect.EnumType {
	return &file_excel_unpriv_rpc_proto_enumTypes[0]
}

func (x ControlAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ControlMsg struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Meta        *GeneralMessageMeta    `protobuf:"bytes,1,opt,name=Meta"`
	xxx_hidden_Action      ControlAction          `protobuf:"varint,2,opt,name=Action,enum=sanitizer_ole.ControlAction"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ControlMsg) Reset() {
	*x = ControlMsg{}
	mi := &file_excel_unpriv_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMsg) ProtoMessage() {}

func (x *ControlMsg) ProtoReflect() protoreflect.Message {
	mi := &file_excel_unpriv_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ControlMsg) GetMeta() *GeneralMessageMeta {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *ControlMsg) GetAction() ControlAction {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Action
		}
	}
	return ControlAction_CONTROL_ACTION_UNKNOWN
}

func (x *ControlMsg) SetMeta(v *GeneralMessageMeta) {
	x.xxx_hidden_Meta = v
}

func (x *ControlMsg) SetAction(v ControlAction) {
	x.xxx_hidden_Action = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ControlMsg) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *ControlMsg) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ControlMsg) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

func (x *ControlMsg) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Action = ControlAction_CONTROL_ACTION_UNKNOWN
}

type ControlMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Meta   *GeneralMessageMeta
	Action *ControlAction
}

func (b0 ControlMsg_builder) Build() *ControlMsg {
	m0 := &ControlMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Meta = b.Meta
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Action = *b.Action
	}
	return m0
}

type SanitizeDocRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Meta          *GeneralMessageMeta    `protobuf:"bytes,1,opt,name=Meta"`
	xxx_hidden_Path          *string                `protobuf:"bytes,2,opt,name=Path"`
	xxx_hidden_Action        *string                `protobuf:"bytes,3,opt,name=Action"`
	xxx_hidden_DetectionName *string                `protobuf:"bytes,4,opt,name=DetectionName"`
	xxx_hidden_DestModule    *string                `protobuf:"bytes,5,opt,name=DestModule"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SanitizeDocRequest) Reset() {
	*x = SanitizeDocRequest{}
	mi := &file_excel_unpriv_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeDocRequest) ProtoMessage() {}

func (x *SanitizeDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_excel_unpriv_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SanitizeDocRequest) GetMeta() *GeneralMessageMeta {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *SanitizeDocRequest) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *SanitizeDocRequest) GetAction() string {
	if x != nil {
		if x.xxx_hidden_Action != nil {
			return *x.xxx_hidden_Action
		}
		return ""
	}
	return ""
}

func (x *SanitizeDocRequest) GetDetectionName() string {
	if x != nil {
		if x.xxx_hidden_DetectionName != nil {
			return *x.xxx_hidden_DetectionName
		}
		return ""
	}
	return ""
}

func (x *SanitizeDocRequest) GetDestModule() string {
	if x != nil {
		if x.xxx_hidden_DestModule != nil {
			return *x.xxx_hidden_DestModule
		}
		return ""
	}
	return ""
}

func (x *SanitizeDocRequest) SetMeta(v *GeneralMessageMeta) {
	x.xxx_hidden_Meta = v
}

func (x *SanitizeDocRequest) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *SanitizeDocRequest) SetAction(v string) {
	x.xxx_hidden_Action = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *SanitizeDocRequest) SetDetectionName(v string) {
	x.xxx_hidden_DetectionName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *SanitizeDocRequest) SetDestModule(v string) {
	x.xxx_hidden_DestModule = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *SanitizeDocRequest) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *SanitizeDocRequest) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SanitizeDocRequest) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SanitizeDocRequest) HasDetectionName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SanitizeDocRequest) HasDestModule() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SanitizeDocRequest) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

func (x *SanitizeDocRequest) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Path = nil
}

func (x *SanitizeDocRequest) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Action = nil
}

func (x *SanitizeDocRequest) ClearDetectionName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_DetectionName = nil
}

func (x *SanitizeDocRequest) ClearDestModule() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DestModule = nil
}

type SanitizeDocRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Meta          *GeneralMessageMeta
	Path          *string
	Action        *string
	DetectionName *string
	DestModule    *string
}

func (b0 SanitizeDocRequest_builder) Build() *SanitizeDocRequest {
	m0 := &SanitizeDocRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Meta = b.Meta
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Path = b.Path
	}
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Action = b.Action
	}
	if b.DetectionName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_DetectionName = b.DetectionName
	}
	if b.DestModule != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_DestModule = b.DestModule
	}
	return m0
}

type UniversalResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Meta          *GeneralMessageMeta    `protobuf:"bytes,1,opt,name=Meta"`
	xxx_hidden_ResultCode    uint32                 `protobuf:"varint,2,opt,name=ResultCode"`
	xxx_hidden_AdditionalMsg *string                `protobuf:"bytes,3,opt,name=AdditionalMsg"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UniversalResponse) Reset() {
	*x = UniversalResponse{}
	mi := &file_excel_unpriv_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalResponse) ProtoMessage() {}

func (x *UniversalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_excel_unpriv_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UniversalResponse) GetMeta() *GeneralMessageMeta {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return nil
}

func (x *UniversalResponse) GetResultCode() uint32 {
	if x != nil {
		return x.xxx_hidden_ResultCode
	}
	return 0
}

func (x *UniversalResponse) GetAdditionalMsg() string {
	if x != nil {
		if x.xxx_hidden_AdditionalMsg != nil {
			return *x.xxx_hidden_AdditionalMsg
		}
		return ""
	}
	return ""
}

func (x *UniversalResponse) SetMeta(v *GeneralMessageMeta) {
	x.xxx_hidden_Meta = v
}

func (x *UniversalResponse) SetResultCode(v uint32) {
	x.xxx_hidden_ResultCode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UniversalResponse) SetAdditionalMsg(v string) {
	x.xxx_hidden_AdditionalMsg = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UniversalResponse) HasMeta() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Meta != nil
}

func (x *UniversalResponse) HasResultCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UniversalResponse) HasAdditionalMsg() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UniversalResponse) ClearMeta() {
	x.xxx_hidden_Meta = nil
}

func (x *UniversalResponse) ClearResultCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResultCode = 0
}

func (x *UniversalResponse) ClearAdditionalMsg() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AdditionalMsg = nil
}

type UniversalResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Meta          *GeneralMessageMeta
	ResultCode    *uint32
	AdditionalMsg *string
}

func (b0 UniversalResponse_builder) Build() *UniversalResponse {
	m0 := &UniversalResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Meta = b.Meta
	if b.ResultCode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ResultCode = *b.ResultCode
	}
	if b.AdditionalMsg != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_AdditionalMsg = b.AdditionalMsg
	}
	return m0
}

type GeneralMessageMeta struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageID   uint64                 `protobuf:"varint,1,opt,name=MessageID"`
	xxx_hidden_ClientID    *string                `protobuf:"bytes,2,opt,name=ClientID"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GeneralMessageMeta) Reset() {
	*x = GeneralMessageMeta{}
	mi := &file_excel_unpriv_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralMessageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralMessageMeta) ProtoMessage() {}

func (x *GeneralMessageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_excel_unpriv_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GeneralMessageMeta) GetMessageID() uint64 {
	if x != nil {
		return x.xxx_hidden_MessageID
	}
	return 0
}

func (x *GeneralMessageMeta) GetClientID() string {
	if x != nil {
		if x.xxx_hidden_ClientID != nil {
			return *x.xxx_hidden_ClientID
		}
		return ""
	}
	return ""
}

func (x *GeneralMessageMeta) SetMessageID(v uint64) {
	x.xxx_hidden_MessageID = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *GeneralMessageMeta) SetClientID(v string) {
	x.xxx_hidden_ClientID = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GeneralMessageMeta) HasMessageID() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GeneralMessageMeta) HasClientID() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GeneralMessageMeta) ClearMessageID() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MessageID = 0
}

func (x *GeneralMessageMeta) ClearClientID() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClientID = nil
}

type GeneralMessageMeta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageID *uint64
	ClientID  *string
}

func (b0 GeneralMessageMeta_builder) Build() *GeneralMessageMeta {
	m0 := &GeneralMessageMeta{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MessageID != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_MessageID = *b.MessageID
	}
	if b.ClientID != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ClientID = b.ClientID
	}
	return m0
}

var File_excel_unpriv_rpc_proto protoreflect.FileDescriptor

const file_excel_unpriv_rpc_proto_rawDesc = "" +
	"\n" +
	"\x16excel_unpriv_rpc.proto\x12\rsanitizer_ole\x1a!google/protobuf/go_features.proto\"y\n" +
	"\n" +
	"ControlMsg\x125\n" +
	"\x04Meta\x18\x01 \x01(\v2!.sanitizer_ole.GeneralMessageMetaR\x04Meta\x124\n" +
	"\x06Action\x18\x02 \x01(\x0e2\x1c.sanitizer_ole.ControlActionR\x06Action\"\xbd\x01\n" +
	"\x12SanitizeDocRequest\x125\n" +
	"\x04Meta\x18\x01 \x01(\v2!.sanitizer_ole.GeneralMessageMetaR\x04Meta\x12\x12\n" +
	"\x04Path\x18\x02 \x01(\tR\x04Path\x12\x16\n" +
	"\x06Action\x18\x03 \x01(\tR\x06Action\x12$\n" +
	"\rDetectionName\x18\x04 \x01(\tR\rDetectionName\x12\x1e\n" +
	"\n" +
	"DestModule\x18\x05 \x01(\tR\n" +
	"DestModule\"\x90\x01\n" +
	"\x11UniversalResponse\x125\n" +
	"\x04Meta\x18\x01 \x01(\v2!.sanitizer_ole.GeneralMessageMetaR\x04Meta\x12\x1e\n" +
	"\n" +
	"ResultCode\x18\x02 \x01(\rR\n" +
	"ResultCode\x12$\n" +
	"\rAdditionalMsg\x18\x03 \x01(\tR\rAdditionalMsg\"N\n" +
	"\x12GeneralMessageMeta\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x04R\tMessageID\x12\x1a\n" +
	"\bClientID\x18\x02 \x01(\tR\bClientID*?\n" +
	"\rControlAction\x12\x1a\n" +
	"\x16CONTROL_ACTION_UNKNOWN\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\b\n" +
	"\x04QUIT\x10\x022\xc2\x01\n" +
	"\x11ExcelSanitizerRPC\x12N\n" +
	"\rControlServer\x12\x19.sanitizer_ole.ControlMsg\x1a .sanitizer_ole.UniversalResponse\"\x00\x12]\n" +
	"\x10SanitizeDocument\x12!.sanitizer_ole.SanitizeDocRequest\x1a .sanitizer_ole.UniversalResponse\"\x00(\x010\x01B\x11Z\a./pbrpc\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_excel_unpriv_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_excel_unpriv_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_excel_unpriv_rpc_proto_goTypes = []any{
	(ControlAction)(0),         // 0: sanitizer_ole.ControlAction
	(*ControlMsg)(nil),         // 1: sanitizer_ole.ControlMsg
	(*SanitizeDocRequest)(nil), // 2: sanitizer_ole.SanitizeDocRequest
	(*UniversalResponse)(nil),  // 3: sanitizer_ole.UniversalResponse
	(*GeneralMessageMeta)(nil), // 4: sanitizer_ole.GeneralMessageMeta
}
var file_excel_unpriv_rpc_proto_depIdxs = []int32{
	4, // 0: sanitizer_ole.ControlMsg.Meta:type_name -> sanitizer_ole.GeneralMessageMeta
	0, // 1: sanitizer_ole.ControlMsg.Action:type_name -> sanitizer_ole.ControlAction
	4, // 2: sanitizer_ole.SanitizeDocRequest.Meta:type_name -> sanitizer_ole.GeneralMessageMeta
	4, // 3: sanitizer_ole.UniversalResponse.Meta:type_name -> sanitizer_ole.GeneralMessageMeta
	1, // 4: sanitizer_ole.ExcelSanitizerRPC.ControlServer:input_type -> sanitizer_ole.ControlMsg
	2, // 5: sanitizer_ole.ExcelSanitizerRPC.SanitizeDocument:input_type -> sanitizer_ole.SanitizeDocRequest
	3, // 6: sanitizer_ole.ExcelSanitizerRPC.ControlServer:output_type -> sanitizer_ole.UniversalResponse
	3, // 7: sanitizer_ole.ExcelSanitizerRPC.SanitizeDocument:output_type -> sanitizer_ole.UniversalResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_excel_unpriv_rpc_proto_init() }
func file_excel_unpriv_rpc_proto_init() {
	if File_excel_unpriv_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_excel_unpriv_rpc_proto_rawDesc), len(file_excel_unpriv_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_excel_unpriv_rpc_proto_goTypes,
		DependencyIndexes: file_excel_unpriv_rpc_proto_depIdxs,
		EnumInfos:         file_excel_unpriv_rpc_proto_enumTypes,
		MessageInfos:      file_excel_unpriv_rpc_proto_msgTypes,
	}.Build()
	File_excel_unpriv_rpc_proto = out.File
	file_excel_unpriv_rpc_proto_goTypes = nil
	file_excel_unpriv_rpc_proto_depIdxs = nil
}
