name: Binary Build (Yara)

on:
  push:
    branches:
      - 'v3_comapi'
    tags:
      - 'v0.4.*'
  pull_request:
    types:
      - ready_for_review
      - opened
    branches:
      - 'v3_comapi'

permissions:
  contents: write

env:
  GO_VER: "1.24.4"
  YARA_VER: "4.3.2"
  PROJECT_DEST: "/opt/buildtargets"
  PROJECT_NAME: "cramc_go"
  THIRD_PARTY_SRC: "/opt/softsrcs"
  CGO_ENABLED: 1

jobs:
  build-linux-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Workaround for git describe
        run: git fetch --prune --unshallow --tags
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache-dependency-path: "gocode/go.sum"
      - name: Introduce Build Envvar
        run: |
          echo "YARA_SRC=${THIRD_PARTY_SRC}/yara/yara-${YARA_VER}" >> $GITHUB_ENV
          echo "PROJ_PREFIX_LINUX_MUSL=${PROJECT_DEST}/${PROJECT_NAME}/musl_linux_amd64" >> $GITHUB_ENV
          echo "YARA_BUILD_LINUX_MUSL=${PROJECT_DEST}/yara/musl_linux_amd64" >> $GITHUB_ENV
      - name: Install Build Deps
        run: |
          sudo apt update -y
          sudo apt install gcc-mingw-w64-x86-64 build-essential pkg-config libyara-dev git zlib1g-dev libbz2-dev libmagic-dev autoconf libtool curl ca-certificates libjansson-dev flex bison libzstd-dev libssl-dev musl-tools upx -y
          go install github.com/tc-hib/go-winres@latest
          mkdir -p ${THIRD_PARTY_SRC} ${PROJ_PREFIX_LINUX_MUSL} ${YARA_BUILD_LINUX_MUSL} ${PROJECT_DEST}
      - name: Fetch Yara src
        run: |
          mkdir -p ${THIRD_PARTY_SRC}/yara
          cd ${THIRD_PARTY_SRC}
          curl -L -O https://github.com/VirusTotal/yara/archive/refs/tags/v${YARA_VER}.tar.gz
          mv ./v${YARA_VER}.tar.gz ./yara-v${YARA_VER}.tar.gz
          tar -xzvf yara-v${YARA_VER}.tar.gz -C ${THIRD_PARTY_SRC}/yara
          rm -rf ./yara-v${YARA_VER}.tar.gz
          cd ${THIRD_PARTY_SRC}/yara/yara-${YARA_VER}
      - name: Workaround for linux-libc-dev magic.h
        run: |
          sudo mkdir -p /usr/include/x86_64-linux-musl/linux
          sudo cp -a /usr/include/linux/magic.h /usr/include/x86_64-linux-musl/linux/magic.h
      - name: Build Yara
        run: |
          cd ${THIRD_PARTY_SRC}/yara/yara-${YARA_VER}
          ./bootstrap.sh
          ( cd ${YARA_BUILD_LINUX_MUSL} && \
            ${YARA_SRC}/configure CC=musl-gcc --prefix=${PROJ_PREFIX_LINUX_MUSL} )
          make -C ${YARA_BUILD_LINUX_MUSL} install
      - name: Build Golang Program
        run: |
          cd ${GITHUB_WORKSPACE}/gocode
          mkdir -p ../bin
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CC=musl-gcc PKG_CONFIG_PATH=${PROJ_PREFIX_LINUX_MUSL}/lib/pkgconfig go build -trimpath -ldflags "-s -w -X \"cramc_go/common.VersionStr=$(git describe --long --dirty --tags)\" -extldflags \"-static\"" -tags yara_static -o ../bin/devreleaser ./cmd/devreleaser
      - name: Autoupdate of Yara Database and Cleanup Database
        run: |
          cp -ar ${GITHUB_WORKSPACE}/bin/devreleaser ${GITHUB_WORKSPACE}/assets
          cd ${GITHUB_WORKSPACE}/assets
          ./devreleaser -compile
          ./devreleaser -enc=true -in=./yrules/bin/unified.yar -out=../bin/unified.yar.bin
          ./devreleaser -enc=true -in=./cramc_db.json -out=../bin/cramc_db.bin
          rm -f ./devreleaser
          cd ${GITHUB_WORKSPACE}/bin
          mv ./devreleaser ./devreleaser_musl_linux_amd64
          upx ./devreleaser_musl_linux_amd64
          ls -alh ${GITHUB_WORKSPACE}/bin
      - name: Upload Runtime Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: database_updates
          retention-days: 30
          path: ${{ github.workspace }}/bin/*.bin
      - name: Upload DevReleaser Artifact
        uses: actions/upload-artifact@v4
        with:
          name: devreleaser
          retention-days: 30
          path: ${{ github.workspace }}/bin/devreleaser_musl_linux_amd64

  build-windows-amd64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Workaround for git describe
        run: git fetch --prune --unshallow --tags
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          cache-dependency-path: "gocode/go.sum"
      - name: Introduce Build Envvar
        run: |
          echo "YARA_SRC=${THIRD_PARTY_SRC}/yara/yara-${YARA_VER}" >> $GITHUB_ENV
          echo "PROJ_PREFIX_WIN64=${PROJECT_DEST}/${PROJECT_NAME}/win64" >> $GITHUB_ENV
          echo "YARA_BUILD_WIN64=${PROJECT_DEST}/yara/win64" >> $GITHUB_ENV
      - name: Install Build Deps
        run: |
          sudo apt update -y
          sudo apt install gcc-mingw-w64-x86-64 build-essential pkg-config libyara-dev git zlib1g-dev libbz2-dev libmagic-dev autoconf libtool curl ca-certificates libjansson-dev flex bison libzstd-dev libssl-dev musl-tools upx -y
          go install github.com/tc-hib/go-winres@latest
          mkdir -p ${THIRD_PARTY_SRC} ${PROJ_PREFIX_WIN64} ${YARA_BUILD_WIN64} ${PROJECT_DEST}
      - name: Fetch Yara src
        run: |
          mkdir -p ${THIRD_PARTY_SRC}/yara
          cd ${THIRD_PARTY_SRC}
          curl -L -O https://github.com/VirusTotal/yara/archive/refs/tags/v${YARA_VER}.tar.gz
          mv ./v${YARA_VER}.tar.gz ./yara-v${YARA_VER}.tar.gz
          tar -xzvf yara-v${YARA_VER}.tar.gz -C ${THIRD_PARTY_SRC}/yara
          rm -rf ./yara-v${YARA_VER}.tar.gz
          cd ${THIRD_PARTY_SRC}/yara/yara-${YARA_VER}
      - name: Workaround for linux-libc-dev magic.h
        run: |
          sudo mkdir -p /usr/include/x86_64-linux-musl/linux
          sudo cp -a /usr/include/linux/magic.h /usr/include/x86_64-linux-musl/linux/magic.h
      - name: Build Yara
        run: |
          cd ${THIRD_PARTY_SRC}/yara/yara-${YARA_VER}
          ./bootstrap.sh
          ( cd ${YARA_BUILD_WIN64} && \
            ${YARA_SRC}/configure --host=x86_64-w64-mingw32 --prefix=${PROJ_PREFIX_WIN64} )
          make -C ${YARA_BUILD_WIN64} install
      - name: Golang Exe WinRES
        run: |
          cd ${GITHUB_WORKSPACE}/gocode/cmd/aioagent
          GOOS=windows GOARCH=amd64 go-winres make --product-version=git-tag
      - name: Build Golang Program
        run: |
          cd ${GITHUB_WORKSPACE}/gocode
          mkdir -p ../bin
          GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc PKG_CONFIG_PATH=${PROJ_PREFIX_WIN64}/lib/pkgconfig go build -trimpath -ldflags "-s -w -X \"cramc_go/common.VersionStr=$(git describe --long --dirty --tags)\" -extldflags \"-static\"" -tags yara_static -o ../bin/cramc_aio.exe ./cmd/aioagent
      - name: Compress of Windows Executables
        run: |
          cd ${GITHUB_WORKSPACE}/bin
          upx ./cramc_aio.exe
          ls -alh ${GITHUB_WORKSPACE}/bin
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cramc_win_aioagent
          retention-days: 30
          path: ${{ github.workspace }}/bin/cramc_aio.exe

  release-to-public:
    needs:
      - build-linux-amd64
      - build-windows-amd64
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare for release
        run: |
          mkdir -p /tmp/relbuild/${{ github.repository_owner }}
      - name: Download artifacts previously generated
        uses: actions/download-artifact@v4
        with:
          path: /tmp/relbuild/${{ github.repository_owner }}
          merge-multiple: true
      - name: List all artifacts downloaded
        run: |
          ls -alh /tmp/relbuild/**/*
      - name: Craft release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          body: |
            We recommend everyone stays on the latest version. 
            To use, download `*.bin` and `cramc_aio.exe` together, then put them under the same new empty folder and execute under that folder. 
            Program will try auto-elevate based on your current privileges. 
            Do not reuse `*.bin` generated from v0.5.x in v0.4.x executables.
          allowUpdates: true
          makeLatest: true
          artifacts: /tmp/relbuild/${{ github.repository_owner }}/*